### ISSUE TITLE
Flatten all dictionary variables

### ISSUE THREAD

**Issue by manics** [openmicroscopy/infrastructure#36]
Dictionaries can't be merged, which means if you want to change one field you have to specify all fields. Flattening them would make things easier to override. E.g.

```
docker_dns:
  forwarders: 8.8.8.8:53,8.8.4.4:53
  domain: docker.internal
  etcd: etcd1
```

It's not possible to override just `docker_dns.domain`, you have to specify the entire dict.
